declare module 'pivotal-ui/react/flex-grids';
declare module 'pivotal-ui/react/siteframe';
declare module 'pivotal-ui/react/panels';
declare module 'pivotal-ui/css/panels';
declare module 'pivotal-ui/css/images';
declare module 'pivotal-ui/react/images';
declare module 'pivotal-ui/react/grids';
// declare module 'pivotal-ui/css/iconography';
declare module 'pictures/header-retro-shop.png';
// declare module 'pivotal-ui/css/iconography';